/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trec.View;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import trec.Controller.UserController;
import trec.Model.User;

/**
 *
 * @author basic
 */
public class AppHomeForm extends javax.swing.JFrame {

  /**
   * Creates new form AppHomeForm
   */
  public AppHomeForm() {
    initComponents();
    User current_user = UserController.getInstance().getCurrentUser();
    home_menu_bar_adminhub.setVisible(current_user.isAdmin());
    home_greet_label.setText("Hi " + current_user.getFirstName() + ", welcome to T-Rec!");    
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    home_welcome_label = new javax.swing.JLabel();
    home_search_destinations_button = new javax.swing.JButton();
    home_edit_profile_button = new javax.swing.JButton();
    home_evaluate_button = new javax.swing.JButton();
    home_statistics_button = new javax.swing.JButton();
    home_get_recommendations_button = new javax.swing.JButton();
    home_evaluate_hotels_button = new javax.swing.JButton();
    home_acommondations_button = new javax.swing.JButton();
    home_greet_label = new javax.swing.JLabel();
    home_menu_bar = new javax.swing.JMenuBar();
    home_menu_bar_logout = new javax.swing.JMenu();
    home_menu_bar_adminhub = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    home_welcome_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    home_welcome_label.setText("- a tourist recommendation system");

    home_search_destinations_button.setText("Search for destinations");
    home_search_destinations_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        home_search_destinations_buttonMouseClicked(evt);
      }
    });
    home_search_destinations_button.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        home_search_destinations_buttonKeyPressed(evt);
      }
    });

    home_edit_profile_button.setText("Edit profile");
    home_edit_profile_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        home_edit_profile_buttonMouseClicked(evt);
      }
    });
    home_edit_profile_button.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        home_edit_profile_buttonKeyPressed(evt);
      }
    });

    home_evaluate_button.setText("Evaluate interest themes");
    home_evaluate_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        home_evaluate_buttonMouseClicked(evt);
      }
    });

    home_statistics_button.setText("See statistics");
    home_statistics_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        home_statistics_buttonMouseClicked(evt);
      }
    });

    home_get_recommendations_button.setText("Get recommendations");
    home_get_recommendations_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        home_get_recommendations_buttonMouseClicked(evt);
      }
    });

    home_evaluate_hotels_button.setText("Evaluate hotels");
    home_evaluate_hotels_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        home_evaluate_hotels_buttonMouseClicked(evt);
      }
    });

    home_acommondations_button.setText("Search for accommondations");
    home_acommondations_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        home_acommondations_buttonMouseClicked(evt);
      }
    });
    home_acommondations_button.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        home_acommondations_buttonKeyPressed(evt);
      }
    });

    home_greet_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    home_greet_label.setText("Hi <first_name>, welcome to T-REC!");

    home_menu_bar_logout.setText("Logout");
    home_menu_bar_logout.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        home_menu_bar_logoutMouseClicked(evt);
      }
    });
    home_menu_bar.add(home_menu_bar_logout);

    home_menu_bar_adminhub.setText("AdminHub");
    home_menu_bar_adminhub.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        home_menu_bar_adminhubMouseClicked(evt);
      }
    });
    home_menu_bar.add(home_menu_bar_adminhub);

    setJMenuBar(home_menu_bar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(46, 46, 46)
            .addComponent(home_welcome_label, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(home_greet_label, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(home_edit_profile_button, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(home_get_recommendations_button, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(home_statistics_button, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(home_evaluate_hotels_button, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(home_evaluate_button, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(home_search_destinations_button, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(home_acommondations_button, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        .addContainerGap(16, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addComponent(home_greet_label)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(home_welcome_label)
        .addGap(27, 27, 27)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(home_edit_profile_button)
          .addComponent(home_acommondations_button))
        .addGap(21, 21, 21)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(home_get_recommendations_button)
          .addComponent(home_search_destinations_button))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(home_statistics_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(home_evaluate_button))
        .addGap(18, 18, 18)
        .addComponent(home_evaluate_hotels_button)
        .addContainerGap(26, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

 
  private void home_search_destinations_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_search_destinations_buttonMouseClicked
    // TODO add your handling code here:
    DestinationsForm destinations_form = new DestinationsForm();
    destinations_form.setVisible(true);
    destinations_form.pack();
    destinations_form.setLocationRelativeTo(null);
    destinations_form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_home_search_destinations_buttonMouseClicked

  private void home_edit_profile_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_edit_profile_buttonMouseClicked
    // TODO add your handling code here:
    if(UserController.getInstance().getCurrentUser().isAdmin()) {
      EditProfileFormAdmin editProfileFormAdmin = new EditProfileFormAdmin();
      editProfileFormAdmin.setVisible(true);
      editProfileFormAdmin.pack();
      editProfileFormAdmin.setLocationRelativeTo(null);
      editProfileFormAdmin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      this.dispose();
    } else {
      EditProfileFormUser editProfileFormUser = new EditProfileFormUser();
      editProfileFormUser.setVisible(true);
      editProfileFormUser.pack();
      editProfileFormUser.setLocationRelativeTo(null);
      editProfileFormUser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      this.dispose();
    }
  }//GEN-LAST:event_home_edit_profile_buttonMouseClicked

  private void home_evaluate_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_evaluate_buttonMouseClicked
    // TODO add your handling code here:
  }//GEN-LAST:event_home_evaluate_buttonMouseClicked

  private void home_statistics_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_statistics_buttonMouseClicked
    // TODO add your handling code here:
  }//GEN-LAST:event_home_statistics_buttonMouseClicked

  private void home_get_recommendations_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_get_recommendations_buttonMouseClicked
    // TODO add your handling code here:
  }//GEN-LAST:event_home_get_recommendations_buttonMouseClicked

  private void home_menu_bar_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_menu_bar_logoutMouseClicked
    // TODO add your handling code here:
    LoginForm login_form = new LoginForm();
    login_form.setVisible(true);
    login_form.pack();
    login_form.setLocationRelativeTo(null);
    login_form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_home_menu_bar_logoutMouseClicked

  private void home_evaluate_hotels_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_evaluate_hotels_buttonMouseClicked
    // TODO add your handling code here:
  }//GEN-LAST:event_home_evaluate_hotels_buttonMouseClicked

  private void home_acommondations_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_acommondations_buttonMouseClicked
    // TODO add your handling code here:
    AccommondationsForm acmd_form = new AccommondationsForm();
    acmd_form.setVisible(true);
    acmd_form.pack();
    acmd_form.setLocationRelativeTo(null);
    acmd_form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_home_acommondations_buttonMouseClicked

  private void home_menu_bar_adminhubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_menu_bar_adminhubMouseClicked
    // TODO add your handling code here:
    AdminHub admin_hub = new AdminHub();
    admin_hub.setVisible(true);
    admin_hub.pack();
    admin_hub.setLocationRelativeTo(null);
    admin_hub.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_home_menu_bar_adminhubMouseClicked

  private void home_edit_profile_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_home_edit_profile_buttonKeyPressed
    // TODO add your handling code here:
    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      home_edit_profile_buttonMouseClicked(null);
    }
  }//GEN-LAST:event_home_edit_profile_buttonKeyPressed

  private void home_acommondations_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_home_acommondations_buttonKeyPressed
    // TODO add your handling code here:
    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      home_acommondations_buttonMouseClicked(null);
    }
  }//GEN-LAST:event_home_acommondations_buttonKeyPressed

  private void home_search_destinations_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_home_search_destinations_buttonKeyPressed
    // TODO add your handling code here:
    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      home_search_destinations_buttonMouseClicked(null);
    }
  }//GEN-LAST:event_home_search_destinations_buttonKeyPressed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AppHomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AppHomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AppHomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AppHomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new AppHomeForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton home_acommondations_button;
  private javax.swing.JButton home_edit_profile_button;
  private javax.swing.JButton home_evaluate_button;
  private javax.swing.JButton home_evaluate_hotels_button;
  private javax.swing.JButton home_get_recommendations_button;
  private javax.swing.JLabel home_greet_label;
  private javax.swing.JMenuBar home_menu_bar;
  private javax.swing.JMenu home_menu_bar_adminhub;
  private javax.swing.JMenu home_menu_bar_logout;
  private javax.swing.JButton home_search_destinations_button;
  private javax.swing.JButton home_statistics_button;
  private javax.swing.JLabel home_welcome_label;
  // End of variables declaration//GEN-END:variables
}
