/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trec.View;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import trec.Controller.UserController;
import trec.Model.City;
import trec.Model.Country;
import trec.Model.Destination;

/**
 *
 * @author basic
 */
public class DestinationsForm extends javax.swing.JFrame {
  private Country current_country_;
  /**
   * Creates new form DestinationsForm
   */
  public DestinationsForm() {
    initComponents();
    try {
      destinations_menu_bar_adminhub.setVisible(UserController.getInstance().getCurrentUser().isAdmin());
      ArrayList<Country> country_list = UserController.getInstance().getCountrys();
      if(!country_list.isEmpty()) {
        country_list.forEach((country) -> {
          destinations_country_combo_box.addItem(country.getName());
        });
        current_country_ = country_list.get(0);
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    destinations_choose_country_label = new javax.swing.JLabel();
    destinations_choose_city_label = new javax.swing.JLabel();
    destinations_list_label = new javax.swing.JLabel();
    destinations_country_combo_box = new javax.swing.JComboBox<>();
    destinations_city_combo_box = new javax.swing.JComboBox<>();
    destinations_list_combo_box = new javax.swing.JComboBox<>();
    jScrollPane1 = new javax.swing.JScrollPane();
    destinations_dest_desc_field = new javax.swing.JTextPane();
    destinations_back_button = new javax.swing.JButton();
    destinations_bookmark_button = new javax.swing.JButton();
    home_menu_bar = new javax.swing.JMenuBar();
    destinations_menu_bar_logout = new javax.swing.JMenu();
    destinations_menu_bar_adminhub = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    destinations_choose_country_label.setText("Choose your destination country:");

    destinations_choose_city_label.setText("Choose a city:");

    destinations_list_label.setText("List of destinations:");

    destinations_country_combo_box.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        destinations_country_combo_boxItemStateChanged(evt);
      }
    });

    destinations_city_combo_box.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        destinations_city_combo_boxItemStateChanged(evt);
      }
    });

    destinations_list_combo_box.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        destinations_list_combo_boxItemStateChanged(evt);
      }
    });

    destinations_dest_desc_field.setEditable(false);
    jScrollPane1.setViewportView(destinations_dest_desc_field);

    destinations_back_button.setText("Back");
    destinations_back_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        destinations_back_buttonMouseClicked(evt);
      }
    });

    destinations_bookmark_button.setText("Bookmark");
    destinations_bookmark_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        destinations_bookmark_buttonMouseClicked(evt);
      }
    });

    destinations_menu_bar_logout.setText("Logout");
    destinations_menu_bar_logout.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        destinations_menu_bar_logoutMouseClicked(evt);
      }
    });
    home_menu_bar.add(destinations_menu_bar_logout);

    destinations_menu_bar_adminhub.setText("AdminHub");
    destinations_menu_bar_adminhub.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        destinations_menu_bar_adminhubMouseClicked(evt);
      }
    });
    home_menu_bar.add(destinations_menu_bar_adminhub);

    setJMenuBar(home_menu_bar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(destinations_back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(181, 181, 181)
            .addComponent(destinations_bookmark_button, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(destinations_choose_country_label)
                .addComponent(destinations_choose_city_label)
                .addComponent(destinations_list_label))
              .addGap(18, 18, 18)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(destinations_list_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(destinations_city_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(destinations_country_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        .addContainerGap(17, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(destinations_choose_country_label)
          .addComponent(destinations_country_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(destinations_choose_city_label)
          .addComponent(destinations_city_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(destinations_list_label)
          .addComponent(destinations_list_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(destinations_back_button)
          .addComponent(destinations_bookmark_button))
        .addContainerGap(20, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void destinations_menu_bar_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destinations_menu_bar_logoutMouseClicked
    // TODO add your handling code here:
    LoginForm login_form = new LoginForm();
    login_form.setVisible(true);
    login_form.pack();
    login_form.setLocationRelativeTo(null);
    login_form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_destinations_menu_bar_logoutMouseClicked

  private void destinations_back_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destinations_back_buttonMouseClicked
    // TODO add your handling code here:
    AppHomeForm app_home_form = new AppHomeForm();
    app_home_form.setVisible(true);
    app_home_form.pack();
    app_home_form.setLocationRelativeTo(null);
    app_home_form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_destinations_back_buttonMouseClicked

  private void destinations_bookmark_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destinations_bookmark_buttonMouseClicked
    // TODO add your handling code here:
    try {
      Destination destination = UserController.getInstance().getDestinationByName(destinations_list_combo_box.getSelectedItem().toString());
      if(UserController.getInstance().addDestinationBookmark(destination, 
              UserController.getInstance().getCurrentUser())) {
        JOptionPane.showMessageDialog(null, "Bookmark added!", "Success!", JOptionPane.INFORMATION_MESSAGE);
      } else {
        JOptionPane.showMessageDialog(null, "Bookmark already exists!", "Bookmark error", JOptionPane.ERROR_MESSAGE);
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }//GEN-LAST:event_destinations_bookmark_buttonMouseClicked

  private void destinations_menu_bar_adminhubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destinations_menu_bar_adminhubMouseClicked
    // TODO add your handling code here:
    AdminHub admin_hub = new AdminHub();
    admin_hub.setVisible(true);
    admin_hub.pack();
    admin_hub.setLocationRelativeTo(null);
    admin_hub.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_destinations_menu_bar_adminhubMouseClicked

  private void destinations_country_combo_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_destinations_country_combo_boxItemStateChanged
    // TODO add your handling code here:
    try {
      String current_country_name = destinations_country_combo_box.getSelectedItem().toString();
      current_country_ = UserController.getInstance().getCountryByName(current_country_name); 
      ArrayList<City> city_list = UserController.getInstance().getCitiesByCountryID(current_country_.getID());
      destinations_city_combo_box.removeAllItems();
      city_list.forEach((city) -> {
        destinations_city_combo_box.addItem(city.getName());
      });

      destinations_list_combo_box.removeAllItems();
      ArrayList<Destination> destination_list = UserController.getInstance().getDestinationByCityID(city_list.get(0).getID());
      if(destination_list.isEmpty()) {
        destinations_dest_desc_field.setText("No item selected.");
      } else {
        destination_list.forEach((destination) -> {
          destinations_list_combo_box.addItem(destination.getName());
        });
        destinations_dest_desc_field.setText(destination_list.get(0).getDescription());
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }//GEN-LAST:event_destinations_country_combo_boxItemStateChanged

  private void destinations_city_combo_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_destinations_city_combo_boxItemStateChanged
    // TODO add your handling code here:
    try {
      ArrayList<City> city_list = UserController.getInstance().getCitiesByCountryID(current_country_.getID());
      int index = destinations_city_combo_box.getSelectedIndex();
      City current_city;
      if(index >= 0)
        current_city = city_list.get(index);
      else
        current_city = city_list.get(0);
      destinations_list_combo_box.removeAllItems();
      ArrayList<Destination> destination_list = UserController.getInstance().getDestinationByCityID(current_city.getID());
      if(!destination_list.isEmpty()) {
        destination_list.forEach((destination) -> {
          destinations_list_combo_box.addItem(destination.getName());
        });
        destinations_dest_desc_field.setText(destination_list.get(0).getDescription());
      } else {
        destinations_dest_desc_field.setText("No item selected");
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }//GEN-LAST:event_destinations_city_combo_boxItemStateChanged

  private void destinations_list_combo_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_destinations_list_combo_boxItemStateChanged
    // TODO add your handling code here:
    try {
      ArrayList<City> city_list = UserController.getInstance().getCitiesByCountryID(current_country_.getID());
      City current_city = city_list.get(destinations_city_combo_box.getSelectedIndex());
      ArrayList<Destination> destination_list = UserController.getInstance().getDestinationByCityID(current_city.getID());
      if(destination_list.isEmpty()) {
        destinations_dest_desc_field.setText("No item selected.");
      } else {
        int index = destinations_list_combo_box.getSelectedIndex();
        if(index >= 0)
          destinations_dest_desc_field.setText(destination_list.get(index).getDescription());
        else
          destinations_dest_desc_field.setText("No item selected.");
      }   
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }//GEN-LAST:event_destinations_list_combo_boxItemStateChanged

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(DestinationsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(DestinationsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(DestinationsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(DestinationsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new DestinationsForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton destinations_back_button;
  private javax.swing.JButton destinations_bookmark_button;
  private javax.swing.JLabel destinations_choose_city_label;
  private javax.swing.JLabel destinations_choose_country_label;
  private javax.swing.JComboBox<String> destinations_city_combo_box;
  private javax.swing.JComboBox<String> destinations_country_combo_box;
  private javax.swing.JTextPane destinations_dest_desc_field;
  private javax.swing.JComboBox<String> destinations_list_combo_box;
  private javax.swing.JLabel destinations_list_label;
  private javax.swing.JMenu destinations_menu_bar_adminhub;
  private javax.swing.JMenu destinations_menu_bar_logout;
  private javax.swing.JMenuBar home_menu_bar;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
