/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trec.View;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import trec.Controller.UserController;
import trec.Model.User;

/**
 *
 * @author basic
 */
public class FriendsForm extends javax.swing.JFrame {
  private ArrayList<Integer> friends_id = new ArrayList<>();
  private User current_user;
  /**
   * Creates new form Friends
   */
  public FriendsForm() {
    initComponents();
    try {
      current_user = UserController.getInstance().getCurrentUser();
      home_menu_bar_adminhub.setVisible(current_user.isAdmin());
      System.out.println("get friends");
      friends_id = UserController.getInstance().getFriends(UserController.getInstance().getCurrentUser().getID());
      System.out.println("get requests");
      ArrayList<Integer> requests = UserController.getInstance().getAllFriendRequests(current_user.getID());
      System.out.println("requests size " + friends_id.size());
      number_of_requests_label.setText(String.valueOf(requests.size()));
      if(friends_id.isEmpty()) {
        name_label.setText("--");
        age_label.setText("--");
        email_label.setText("--");
        occupation_label.setText("--");
      } else {
        for(int id : friends_id) {
          friends_combo_box.addItem(UserController.getInstance().getUserByUserID(id).getUsername());
        }
        User first_user = UserController.getInstance().getUserByUserID(friends_id.get(0));
        name_label.setText(first_user.getFirstName() + " " + first_user.getLastName());
        age_label.setText(String.valueOf(first_user.getAge()));
        email_label.setText(first_user.getEmail());
        occupation_label.setText(first_user.getOccupation());
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
  
  public void refresh() {
    FriendsForm form = new FriendsForm();
    form.setVisible(true);
    form.pack();
    form.setLocationRelativeTo(null);
    form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    back_button = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    send_request_button = new javax.swing.JButton();
    insert_username_field = new javax.swing.JTextField();
    show_requests_button = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    friends_combo_box = new javax.swing.JComboBox<>();
    delete_friend_button = new javax.swing.JButton();
    send_message_label = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    name_label = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    number_of_requests_label = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    email_label = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    occupation_label = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    age_label = new javax.swing.JLabel();
    adminhub_menu_bar = new javax.swing.JMenuBar();
    adminhub_menu_bar_logout = new javax.swing.JMenu();
    home_menu_bar_adminhub = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    back_button.setText("Back");
    back_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        back_buttonMouseClicked(evt);
      }
    });

    jLabel1.setText("Add new friend:");

    send_request_button.setText("Send request");
    send_request_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        send_request_buttonMouseClicked(evt);
      }
    });

    show_requests_button.setText("Show friend requests");
    show_requests_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        show_requests_buttonMouseClicked(evt);
      }
    });

    jLabel2.setText("My friends:");

    friends_combo_box.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        friends_combo_boxItemStateChanged(evt);
      }
    });

    delete_friend_button.setText("Delete friend");
    delete_friend_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        delete_friend_buttonMouseClicked(evt);
      }
    });

    send_message_label.setText("Send a message");
    send_message_label.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        send_message_labelMouseClicked(evt);
      }
    });

    jLabel3.setText("Name:");

    name_label.setText("<first_name> <second_name>");

    jLabel5.setText("Age:");

    number_of_requests_label.setText("<int>");

    jLabel7.setText("E-mail:");

    email_label.setText("<e-mail>");

    jLabel9.setText("Occupation:");

    occupation_label.setText("<occupation>");

    jLabel10.setText("Current number of requests:");

    age_label.setText("<age>");

    adminhub_menu_bar_logout.setText("Logout");
    adminhub_menu_bar_logout.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        adminhub_menu_bar_logoutMouseClicked(evt);
      }
    });
    adminhub_menu_bar.add(adminhub_menu_bar_logout);

    home_menu_bar_adminhub.setText("AdminHub");
    home_menu_bar_adminhub.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        home_menu_bar_adminhubMouseClicked(evt);
      }
    });
    adminhub_menu_bar.add(home_menu_bar_adminhub);

    setJMenuBar(adminhub_menu_bar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(send_message_label, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
              .addComponent(back_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(number_of_requests_label))
              .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(show_requests_button, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))))
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9)
                .addComponent(jLabel7)
                .addComponent(jLabel5)
                .addComponent(jLabel3))
              .addGap(37, 37, 37)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(age_label)
                .addComponent(name_label)
                .addComponent(email_label)
                .addComponent(occupation_label)))
            .addGroup(layout.createSequentialGroup()
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1)
                .addComponent(jLabel2))
              .addGap(18, 18, 18)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(friends_combo_box, 0, 222, Short.MAX_VALUE)
                .addComponent(insert_username_field))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(send_request_button, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addComponent(delete_friend_button, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(insert_username_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(send_request_button))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(friends_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(delete_friend_button))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(age_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(occupation_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(send_message_label)
          .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(number_of_requests_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(14, 14, 14)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(back_button)
          .addComponent(show_requests_button))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void adminhub_menu_bar_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminhub_menu_bar_logoutMouseClicked
    // TODO add your handling code here:
    LoginForm login_form = new LoginForm();
    login_form.setVisible(true);
    login_form.pack();
    login_form.setLocationRelativeTo(null);
    login_form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_adminhub_menu_bar_logoutMouseClicked

  private void home_menu_bar_adminhubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_menu_bar_adminhubMouseClicked
    // TODO add your handling code here:
    AdminHub admin_hub = new AdminHub();
    admin_hub.setVisible(true);
    admin_hub.pack();
    admin_hub.setLocationRelativeTo(null);
    admin_hub.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_home_menu_bar_adminhubMouseClicked

  private void back_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_buttonMouseClicked
    // TODO add your handling code here:
    AppHomeForm form = new AppHomeForm();
    form.setVisible(true);
    form.pack();
    form.setLocationRelativeTo(null);
    form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_back_buttonMouseClicked

  private void send_request_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_send_request_buttonMouseClicked
    // TODO add your handling code here:
    String username = insert_username_field.getText();
    try {
      User user = UserController.getInstance().getUserByUsername(username);
      if(user != null) {
        UserController.getInstance().sendFriendRequest(current_user.getID(), user.getID());
        JOptionPane.showMessageDialog(null, "Friend request sent to user: " + username + " .", "Request sent!", JOptionPane.INFORMATION_MESSAGE);
        refresh();
      } else {
        JOptionPane.showMessageDialog(null, "User with username: " + username + " does not exist.", "User does not exist.", JOptionPane.ERROR_MESSAGE);
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }//GEN-LAST:event_send_request_buttonMouseClicked

  private void show_requests_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_requests_buttonMouseClicked
    // TODO add your handling code here:\
    FriendRequestsForm form = new FriendRequestsForm();
    form.setVisible(true);
    form.pack();
    form.setLocationRelativeTo(null);
    form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_show_requests_buttonMouseClicked

  private void delete_friend_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_friend_buttonMouseClicked
    // TODO add your handling code here:
    try {
      if(friends_id.isEmpty()) {
        JOptionPane.showMessageDialog(null, "You have no friends!", "Who are you deleting?", JOptionPane.ERROR_MESSAGE);
      } else {
        User target_user = UserController.getInstance().getUserByUsername(friends_combo_box.getSelectedItem().toString());
        UserController.getInstance().deleteFriendRelationship(current_user.getID(), target_user.getID());
        JOptionPane.showMessageDialog(null, "Friend deleted!", "Success!", JOptionPane.INFORMATION_MESSAGE);
        refresh();
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }//GEN-LAST:event_delete_friend_buttonMouseClicked

  private void send_message_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_send_message_labelMouseClicked
    // TODO add your handling code here:
    try {
      String username = friends_combo_box.getSelectedItem().toString();
      User user = UserController.getInstance().getUserByUsername(username);
      SendMessageForm form = new SendMessageForm(user.getID());
      form.setVisible(true);
      form.pack();
      form.setLocationRelativeTo(null);
      form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      this.dispose();
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }//GEN-LAST:event_send_message_labelMouseClicked

  private void friends_combo_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_friends_combo_boxItemStateChanged
    // TODO add your handling code here:
    try {
      String username = friends_combo_box.getSelectedItem().toString();
      User first_user = UserController.getInstance().getUserByUsername(username);
      name_label.setText(first_user.getFirstName() + " " + first_user.getLastName());
      age_label.setText(String.valueOf(first_user.getAge()));
      email_label.setText(first_user.getEmail());
      occupation_label.setText(first_user.getOccupation());
    } catch (Exception e) {
      System.out.println(e.getMessage());
    } 
  }//GEN-LAST:event_friends_combo_boxItemStateChanged

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FriendsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FriendsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FriendsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FriendsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FriendsForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar adminhub_menu_bar;
  private javax.swing.JMenu adminhub_menu_bar_logout;
  private javax.swing.JLabel age_label;
  private javax.swing.JButton back_button;
  private javax.swing.JButton delete_friend_button;
  private javax.swing.JLabel email_label;
  private javax.swing.JComboBox<String> friends_combo_box;
  private javax.swing.JMenu home_menu_bar_adminhub;
  private javax.swing.JTextField insert_username_field;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JLabel name_label;
  private javax.swing.JLabel number_of_requests_label;
  private javax.swing.JLabel occupation_label;
  private javax.swing.JButton send_message_label;
  private javax.swing.JButton send_request_button;
  private javax.swing.JButton show_requests_button;
  // End of variables declaration//GEN-END:variables
}
