/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trec.View;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import trec.Controller.UserController;
import trec.Model.User;

/**
 *
 * @author basic
 */
public class InterestThemesForm extends javax.swing.JFrame {
  /**
   * Creates new form InterestThemesForm
   */
  private ArrayList<String> interest_themes_list = new ArrayList<>();
  private ArrayList<JCheckBox> checkboxes = new ArrayList<>();
  
  public InterestThemesForm() {
    initComponents();
    User current_user = UserController.getInstance().getCurrentUser();
    home_menu_bar_adminhub.setVisible(current_user.isAdmin());
    try {
      interest_themes_list = UserController.getInstance().getAllITs();
      jPanel2.setLayout(new GridLayout(0, 2, 10, 10));
      for (String it : interest_themes_list) {
        JCheckBox cb = new JCheckBox(it);
        checkboxes.add(cb);
        jPanel2.add(cb);
        jPanel2.revalidate();
        jPanel2.repaint();
      }
      ArrayList<Integer> checked_by_user = UserController.getInstance().getAllITbyUserID(current_user.getID());
      for(int it_id : checked_by_user) {
        for(JCheckBox ch : checkboxes) {
          String it_name = UserController.getInstance().getITNameByID(it_id);
          if(it_name.equals(ch.getText())) {
            ch.setSelected(true);
          }
        }
      }
      
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jPanel2 = new javax.swing.JPanel();
    choose_it_label = new java.awt.Label();
    home_edit_profile_button = new javax.swing.JButton();
    back_button = new javax.swing.JButton();
    save_button = new javax.swing.JButton();
    home_menu_bar = new javax.swing.JMenuBar();
    home_menu_bar_logout = new javax.swing.JMenu();
    home_menu_bar_adminhub = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 378, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 276, Short.MAX_VALUE)
    );

    jScrollPane1.setViewportView(jPanel2);

    choose_it_label.setText("Choose interest themes You are interested in:");

    home_edit_profile_button.setText("Edit profile");
    home_edit_profile_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        home_edit_profile_buttonMouseClicked(evt);
      }
    });
    home_edit_profile_button.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        home_edit_profile_buttonKeyPressed(evt);
      }
    });

    back_button.setText("Back");
    back_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        back_buttonMouseClicked(evt);
      }
    });
    back_button.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        back_buttonKeyPressed(evt);
      }
    });

    save_button.setText("Save");
    save_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        save_buttonMouseClicked(evt);
      }
    });
    save_button.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        save_buttonKeyPressed(evt);
      }
    });

    home_menu_bar_logout.setText("Logout");
    home_menu_bar_logout.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        home_menu_bar_logoutMouseClicked(evt);
      }
    });
    home_menu_bar.add(home_menu_bar_logout);

    home_menu_bar_adminhub.setText("AdminHub");
    home_menu_bar_adminhub.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        home_menu_bar_adminhubMouseClicked(evt);
      }
    });
    home_menu_bar.add(home_menu_bar_adminhub);

    setJMenuBar(home_menu_bar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addComponent(choose_it_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(95, 95, 95)
          .addComponent(home_edit_profile_button, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(95, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(choose_it_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(8, 8, 8)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(back_button)
          .addComponent(save_button))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(128, 128, 128)
          .addComponent(home_edit_profile_button)
          .addContainerGap(100, Short.MAX_VALUE)))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void home_menu_bar_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_menu_bar_logoutMouseClicked
    // TODO add your handling code here:
    LoginForm login_form = new LoginForm();
    login_form.setVisible(true);
    login_form.pack();
    login_form.setLocationRelativeTo(null);
    login_form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_home_menu_bar_logoutMouseClicked

  private void home_menu_bar_adminhubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_menu_bar_adminhubMouseClicked
    // TODO add your handling code here:
    AdminHub admin_hub = new AdminHub();
    admin_hub.setVisible(true);
    admin_hub.pack();
    admin_hub.setLocationRelativeTo(null);
    admin_hub.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_home_menu_bar_adminhubMouseClicked

  private void home_edit_profile_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_edit_profile_buttonMouseClicked
    // TODO add your handling code here:
  }//GEN-LAST:event_home_edit_profile_buttonMouseClicked

  private void home_edit_profile_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_home_edit_profile_buttonKeyPressed
    // TODO add your handling code here:
  }//GEN-LAST:event_home_edit_profile_buttonKeyPressed

  private void back_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_buttonMouseClicked
    // TODO add your handling code here:
    AppHomeForm app_home_form = new AppHomeForm();
    app_home_form.setVisible(true);
    app_home_form.pack();
    app_home_form.setLocationRelativeTo(null);
    app_home_form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_back_buttonMouseClicked

  private void back_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_back_buttonKeyPressed
    // TODO add your handling code here:
    back_buttonMouseClicked(null);
  }//GEN-LAST:event_back_buttonKeyPressed

  private void save_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseClicked
    // TODO add your handling code here:
    try {
      UserController.getInstance().deleteAllUserITs(UserController.getInstance().getCurrentUser().getID());
      for(JCheckBox ch : checkboxes) {
        if (ch.isSelected()) {
          int it_id = UserController.getInstance().getITIDByName(ch.getText());
          UserController.getInstance().addNewITPair(UserController.getInstance().getCurrentUser().getID(), it_id);
        }
      }
      JOptionPane.showMessageDialog(null, "Interest themes saved!", "Success!", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }//GEN-LAST:event_save_buttonMouseClicked

  private void save_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_save_buttonKeyPressed
    // TODO add your handling code here:
    save_buttonMouseClicked(null);
  }//GEN-LAST:event_save_buttonKeyPressed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(InterestThemesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(InterestThemesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(InterestThemesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(InterestThemesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new InterestThemesForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton back_button;
  private java.awt.Label choose_it_label;
  private javax.swing.JButton home_edit_profile_button;
  private javax.swing.JMenuBar home_menu_bar;
  private javax.swing.JMenu home_menu_bar_adminhub;
  private javax.swing.JMenu home_menu_bar_logout;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton save_button;
  // End of variables declaration//GEN-END:variables
}
