/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trec.View;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import trec.Controller.UserController;
import trec.Model.Database;
import trec.Model.User;

/**
 *
 * @author basic
 */
public class LoginForm extends javax.swing.JFrame {
  
  /**
   * Creates new form LoginForm
   */
  public LoginForm() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    login_register_button = new javax.swing.JButton();
    login_login_button = new javax.swing.JButton();
    login_username_label = new javax.swing.JLabel();
    login_password_label = new javax.swing.JLabel();
    login_password_field = new javax.swing.JPasswordField();
    login_username_field = new javax.swing.JFormattedTextField();
    login_trec_welcome_label = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    login_register_button.setText("Register");
    login_register_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        login_register_buttonMouseClicked(evt);
      }
    });
    login_register_button.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        login_register_buttonKeyPressed(evt);
      }
    });

    login_login_button.setText("Log in");
    login_login_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        login_login_buttonMouseClicked(evt);
      }
    });
    login_login_button.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        login_login_buttonKeyPressed(evt);
      }
    });

    login_username_label.setText("Username:");

    login_password_label.setText("Password:");

    login_password_field.setText("jPasswordField1");
    login_password_field.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        login_password_fieldFocusGained(evt);
      }
    });
    login_password_field.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        login_password_fieldKeyPressed(evt);
      }
    });

    login_username_field.setText(" Enter your username");
    login_username_field.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        login_username_fieldFocusGained(evt);
      }
    });
    login_username_field.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        login_username_fieldKeyPressed(evt);
      }
    });

    login_trec_welcome_label.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    login_trec_welcome_label.setText("Welcome to T-REC - a tourist recommendation system");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(login_username_label)
                .addComponent(login_password_label))
              .addGroup(layout.createSequentialGroup()
                .addComponent(login_register_button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)))
            .addGap(47, 47, 47)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(login_login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(login_username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(login_password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(login_trec_welcome_label))
        .addContainerGap(24, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(login_trec_welcome_label)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(login_username_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(login_username_field, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(login_password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(login_password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(login_login_button)
          .addComponent(login_register_button))
        .addGap(17, 17, 17))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void login_register_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_register_buttonMouseClicked
    // TODO add your handling code here:
    RegisterForm register_form = new RegisterForm();
    register_form.setVisible(true);
    register_form.pack();
    register_form.setLocationRelativeTo(null);
    register_form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_login_register_buttonMouseClicked

  private void login_login_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_login_buttonMouseClicked
    // TODO add your handling code here:
    User current_user = Database.getInstance().isUserValid(login_username_field.getText(), String.copyValueOf(login_password_field.getPassword()));
    if(current_user == null) {
      JOptionPane.showMessageDialog(null, "You entered wrong username or password.\nNo account? You can always register.", "Login error", JOptionPane.ERROR_MESSAGE);
    } else {
      UserController.getInstance().setCurrentUser(current_user);
      // activity switch
      AppHomeForm app_home_form = new AppHomeForm();
      app_home_form.setVisible(true);
      app_home_form.pack();
      app_home_form.setLocationRelativeTo(null);
      app_home_form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      this.dispose();
    }
  }//GEN-LAST:event_login_login_buttonMouseClicked

  private void login_login_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_login_buttonKeyPressed
    // TODO add your handling code here:
    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      login_login_buttonMouseClicked(null);
    }
  }//GEN-LAST:event_login_login_buttonKeyPressed

  private void login_password_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_password_fieldKeyPressed
    // TODO add your handling code here:
    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      login_login_buttonMouseClicked(null);
    }
  }//GEN-LAST:event_login_password_fieldKeyPressed

  private void login_username_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_username_fieldKeyPressed
    // TODO add your handling code here:
    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      login_login_buttonMouseClicked(null);
    }
  }//GEN-LAST:event_login_username_fieldKeyPressed

  private void login_register_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_register_buttonKeyPressed
    // TODO add your handling code here:
    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      login_register_buttonMouseClicked(null);
    }
  }//GEN-LAST:event_login_register_buttonKeyPressed

  private void login_username_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_username_fieldFocusGained
    // TODO add your handling code here:
    login_username_field.setText("");
  }//GEN-LAST:event_login_username_fieldFocusGained

  private void login_password_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_password_fieldFocusGained
    // TODO add your handling code here:
    login_password_field.setText("");
  }//GEN-LAST:event_login_password_fieldFocusGained

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new LoginForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton login_login_button;
  private javax.swing.JPasswordField login_password_field;
  private javax.swing.JLabel login_password_label;
  private javax.swing.JButton login_register_button;
  private javax.swing.JLabel login_trec_welcome_label;
  private javax.swing.JFormattedTextField login_username_field;
  private javax.swing.JLabel login_username_label;
  // End of variables declaration//GEN-END:variables
}
