/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trec.View;

import javax.swing.JFrame;
import trec.Model.Helper;
import trec.Model.WeatherModel;


/**
 *
 * @author basic
 */
public class WeatherForm extends javax.swing.JFrame {
  private Helper helper;
  private WeatherModel weather_model;
  private String jform_before_;
  /**
   * Creates new form WeatherFrom
   */
  public WeatherForm() {
    initComponents();
  }
  
  public WeatherForm(String city, String jform_before) {
    initComponents();
    helper = new Helper();
    this.jform_before_ = jform_before;
    try {
      weather_model = helper.getWeather(city);
      temperature_field.setText(weather_model.getTemperature() + "\u00b0C");
      humidity_field.setText(weather_model.getHumidity() + "%");
      temp_max.setText(weather_model.getTempMax() + "\u00b0C");
      temp_min.setText(weather_model.getTempMin() + "\u00b0C");
      description_field.setText(weather_model.getDescription());
      city_field.setText(city);
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    temp_min = new javax.swing.JLabel();
    description_field = new javax.swing.JLabel();
    temperature_field = new javax.swing.JLabel();
    temp_max = new javax.swing.JLabel();
    location = new javax.swing.JLabel();
    humidity_field = new javax.swing.JLabel();
    back_button = new javax.swing.JButton();
    city_field = new javax.swing.JLabel();
    temp_min1 = new javax.swing.JLabel();
    temp_max1 = new javax.swing.JLabel();
    description1 = new javax.swing.JLabel();
    temperature2 = new javax.swing.JLabel();
    temperature3 = new javax.swing.JLabel();
    accommondations_menu_bar = new javax.swing.JMenuBar();
    acommondations_menu_bar_logout = new javax.swing.JMenu();
    acommondations_menu_bar_adminhub = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    temp_min.setText("<min>");

    description_field.setText("<description>");

    temperature_field.setText("<temperature>");

    temp_max.setText("<max>");

    location.setText("Humidity:");

    humidity_field.setText("<humidity>");

    back_button.setText("Back");
    back_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        back_buttonMouseClicked(evt);
      }
    });

    city_field.setText("<city>");

    temp_min1.setText("Minimum temperature:");

    temp_max1.setText("Maximum temperature:");

    description1.setText("Description:");

    temperature2.setText("Temperature:");

    temperature3.setText("Displaying weather for:");

    acommondations_menu_bar_logout.setText("Logout");
    acommondations_menu_bar_logout.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        acommondations_menu_bar_logoutMouseClicked(evt);
      }
    });
    accommondations_menu_bar.add(acommondations_menu_bar_logout);

    acommondations_menu_bar_adminhub.setText("AdminHub");
    acommondations_menu_bar_adminhub.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        acommondations_menu_bar_adminhubMouseClicked(evt);
      }
    });
    accommondations_menu_bar.add(acommondations_menu_bar_adminhub);

    setJMenuBar(accommondations_menu_bar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(temperature3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(city_field))
          .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(temperature2)
              .addComponent(location))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(humidity_field)
              .addComponent(temperature_field)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(description1)
            .addGap(18, 18, 18)
            .addComponent(description_field)
            .addGap(45, 45, 45)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(temp_max1)
              .addComponent(temp_min1))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(temp_max)
              .addComponent(temp_min))))
        .addContainerGap(44, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(city_field, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(temperature3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(description1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(description_field, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(temp_max1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(temp_min, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(temperature2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(temperature_field, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(temp_min1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(temp_max, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(humidity_field, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(back_button)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void acommondations_menu_bar_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acommondations_menu_bar_logoutMouseClicked
    // TODO add your handling code here:
    LoginForm login_form = new LoginForm();
    login_form.setVisible(true);
    login_form.pack();
    login_form.setLocationRelativeTo(null);
    login_form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_acommondations_menu_bar_logoutMouseClicked

  private void acommondations_menu_bar_adminhubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acommondations_menu_bar_adminhubMouseClicked
    // TODO add your handling code here:
    AdminHub admin_hub = new AdminHub();
    admin_hub.setVisible(true);
    admin_hub.pack();
    admin_hub.setLocationRelativeTo(null);
    admin_hub.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
  }//GEN-LAST:event_acommondations_menu_bar_adminhubMouseClicked

  private void back_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_buttonMouseClicked
    // TODO add your handling code here:
    if(jform_before_.equals("accommodations")) {
      AccommondationsForm form = new AccommondationsForm();
      form.setVisible(true);
      form.pack();
      form.setLocationRelativeTo(null);
      form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      this.dispose(); 
    } else if(jform_before_.equals("destinations")) {
      DestinationsForm form = new DestinationsForm();
      form.setVisible(true);
      form.pack();
      form.setLocationRelativeTo(null);
      form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      this.dispose(); 
    }
  }//GEN-LAST:event_back_buttonMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(WeatherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(WeatherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(WeatherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(WeatherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new WeatherForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar accommondations_menu_bar;
  private javax.swing.JMenu acommondations_menu_bar_adminhub;
  private javax.swing.JMenu acommondations_menu_bar_logout;
  private javax.swing.JButton back_button;
  private javax.swing.JLabel city_field;
  private javax.swing.JLabel description1;
  private javax.swing.JLabel description_field;
  private javax.swing.JLabel humidity_field;
  private javax.swing.JLabel location;
  private javax.swing.JLabel temp_max;
  private javax.swing.JLabel temp_max1;
  private javax.swing.JLabel temp_min;
  private javax.swing.JLabel temp_min1;
  private javax.swing.JLabel temperature2;
  private javax.swing.JLabel temperature3;
  private javax.swing.JLabel temperature_field;
  // End of variables declaration//GEN-END:variables
}
